# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tm89WraHxoU8cQUROywsw8ZGFcnsQTyT
"""

# diện tích khu các căn phòng trong nhà
hall = 12.3
kit = 10
liv = 14
bed = 16.5
bath = 17

# các giá trị của các phòng trong nhà
areas = [hall, kit, liv, bed, bath]
# in ra areas
print (areas)

# diện tích khu các căn phòng trong nhà
hall = 12.3
kit = 10
liv = 14
bed = 16.5
bath = 17
# các giá trị của căn phòng
areas = [hall, "hallway" ,kit, "kitchen" ,bed, "bedroom"]
#in ra areas
print (areas)

# diện tích khu các căn phòng trong nhà
hall = 12.3
kit = 10
liv = 14
bed = 16.5
bath = 17
# # danh sách chứa đấy đủ cá phòng
house = [
    [hall, "hallway",' hành lang'],
    [kit, "kitchen" ,' phòng bếp'],
    [liv, "livingroom" ,' phòng khách'],
    [bed, "bedroom", ' phòng ngủ'],
    [bath, "bathroom", ' phòng tắm'],
    ]
# in ra
print (house)

# dữ liệu
areas = [("hallway", "12.3") ,( "kitchen", "10"), ("livingroom", "14")]
# in theo thứ tự thứ nhất
areas[0]
# in theo thứ tự thứ hai
areas[1]
# in theo thứ tự thứ 3
areas[2]

# in ra màn hình
print ( areas [1], areas[0],areas[2] )

# NHẬP DỮ LIỆU
areas = [
    ("hallway", "12.3"),
    ("kitchen", "10"),
    ("livingroom", "14")
]

# Tính tổng diện tích
rest_area = float(areas[0][1]) + float(areas[2][1])

print(rest_area)

# Nhập dữ liệu
areas = [("hallway",10), ("kitchen",12), ("bathroom",13), ("livingroom",14), ("bedroom",15,)]
# trích suất phần tử
downstairs = areas[0:1]
# tầng trên
upstairs = areas[2:3]
# in ra
print(downstairs)
print(upstairs)

