# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCthMNTfgvyrpGXI-mVRvr-Oq42eOw6d
"""

n = int(input("nhập một số nguyên dương:"))
print(n)

s = 0 # biến số dùng để lưu tổng
for i in range (1, n + 1 ):
  s += i
print (f" tổng từ 1 đến {n} là {s}")

n = int(input("Nhập một số nguyên dương: "))
print(n)

s = 0  # biến số dùng để lưu tổng

for i in range(2, n):
    if i % 2 == 0:
        s += i

print(f"Tổng các số chẵn nhỏ hơn {n} là {s}")