# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xsvddd24pbCA08FHkmc1FX4pQGJTFGKN
"""

print("hello")
import math
import sys
a = float (input("a = 2"))
b = float (input("b = 4"))
c = float (input("c= 6"))
print(f"a = {a}, b = {b}, c = {c}")

# Enter your code from here
print("Chuong trinh giải phuong trinh bac 2: ax^2 + bx + c = 0")
delta  = b**2 - 4*a*c
if delta < 0:
  print(f"Phuong trinh co nghiem trong tap so thuc.")
elif delta == 0:
  x = -b / (2*a)
  print(f"phuong trinh nghiem kep: x = {x}")
else:
 x1 = (-b + math.sprt(delta)) / (2*a)
 x2 = (-b - math.sprt(delta)) / (2*a)
 print(" phuong trinh co hai nghiem phan biet.")
 print(f"x1 = {x1}")
 print(f"x2 = {x2}")

